const localizations = {
    shopName: 'MoSBook',
    signin: 'Sign In',
    myAccount: 'My Account',
    basket: 'Basket',
    help: 'Help',
    inputSearchPlaceholder: 'Entey keyword, title, author or ISBN',
    advancedSearch: 'Advanced Search',
    browseCollections: 'Browse Collections',
    rareBooks: 'Rare Books',
    artAndCollectibles: 'Art & Collectibles',
    textBooks: 'Textbooks',
    sellers: 'Sellers',
    startSelling: 'Start Selling',
    searchFormIntro: 'SHOP FROM INDEPENDENT SELLER',
    searchFormHeader: 'Search for books, fine art and collectibles',
    author: 'Author',
    title: 'Title',
    keywordOrISBN: 'Keyword or ISBN',
    search: 'Search',
    searchByAuthor: 'Enter Author',
    searchByTitle: 'Enter Title',
    searchByKeywordOrISBN: 'Enter Keyword or ISBN',
    shopWithUs: 'Shop With Us',
    myOrders: 'My Orders',
    viewBasket: 'View Basket',
    sellWithUs: 'Sell With Us',
    bookBuyBack: 'Book Buyback',
    referASeller: 'Refer A Seller',
    aboutUs: 'About Us',
    aboutMosBooks: 'About MoSBooks',
    media: 'Media',
    careers: 'Careers',
    forums: 'Forums',
    privacyPolicy: 'Privacy Policy',
    designatedAgent: 'Designated Agent',
    accessibility: 'Accessibility',
    findHelp: 'Find Help',
    customerSupport: 'Customer Support',
    followMoSBooks: 'Follow MoSBooks',
    facebook: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    youtube: 'Youtube',
    podcast: 'Podcase',
    copyRight: '© 1996 - 2022 AbeBooks Inc. All Rights Reserved. AbeBooks, the AbeBooks logo, AbeBooks.com, "Passion for books." and "Passion for books. Books for your passion." are registered trademarks with the Registered US Patent & Trademark Office.',
    backToTop: 'Back to top',
    joinOurAffiliateProgram: 'Join Our Affiliate Program',
    termsAndConditions: 'By using the Web site, you confirm that you have read, understood, and agreed to be bound by the Terms and Conditions.',
    email: 'Email',
    password: 'Password',
    signinTermsAndConditions: 'By signing-in, you agree to the AbeBooks.com ',
    keepMeSignedIn: 'Keep me signed in.',
    newToMosBooks: 'New to MoSBooks?',
    createYourMosBooksAccount: 'Create Your MoSBooks Account',
    forgetPassword: 'Forgot your password?',
    createAccount: 'Create account',
    firstAndLastName: 'First and last name',
    atLeast6Charaters: 'At least 6 characters',
    yourName: 'Your Name',
    reEnterPassword: 'Re-enter password',
    alertPassword: 'Passwords must be at least 6 characters',
    alreadyHaveeAnAccount: 'Already have an account?',
    basketItems: 'Basket Items',
    items: 'items',
    item: 'item',
    price: 'Price',
    quantity: 'Quantity',
    remove: 'Remove',
    shipping: 'Shipping',
    subTotal: 'SubTotal',
    total: 'Toal',
    seller: 'Seller',
    publishedBy: 'Published by',
    saveForLater: 'Save for Later',
    from: 'From',
    aboutThisItem: 'About This Item',
    paymentMethods: 'Payment Methods',
    buyNew: 'Buy New',
    within: 'Within',
    addToBasket: 'Add to basket',
    dayReturnPolicy: 'Day Return Policy',
    myPurchases: 'My Purchases',
    myEmails: 'My Emails',
    myPersonalInfo: 'My Personal Info',
    myWants: 'My Wants',
    viewMyShoppingBasket: 'View My Shopping Basket',
    viewMyEmails: 'View My Emails',
    myNameEmailAndPassword: 'My name, email and password',
    myAccountInfo: 'My Account Information',
    myAddressBook: 'My Address Book',
    manageMyCreditCards: 'Manage My Credit Cards',
    listAndMaintainMyWants: 'List and Maintain My Wants',
    myRecentlMatchedWants: 'My Recently Matched Wants',
    learnMoreAboutWants: 'Learn More About Wants',
    downloadMyWantsReport: 'Download My Wants Report',
    moSBooksHelp: 'MoSBooks Help',
    contactCustomerSupport: 'Contact Customer Support',
    communityForums: 'Community Forums',
    changeEmailAddress: 'Change your email address',
    currentEmailAddress: 'Current email address:',
    enterOTP: 'Enter the new email address you would like to associate with your account below. We will send a One Time Password (OTP) to that address.',
    newEmailAddress: 'New Email Address',
    newName: 'New Name',
    continue: 'Continue',
    changeName: 'Change your name',
    changePassword: 'Change password',
    saveChangeName: 'If you want to change the name associated with your AbeBooks customer account, you may do so below. Be sure to click the Save Changes button when you are done.'
};

export default localizations;